# Generated by Django 4.2.7 on 2023-11-28 10:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_description', models.TextField(blank=None, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_description', models.TextField(blank=None, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('time_create', models.TimeField(auto_now_add=True)),
                ('time_update', models.TimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='products_images')),
                ('made_in', models.CharField(max_length=255)),
                ('movement', models.CharField(max_length=255)),
                ('case_material', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('water_resistance', models.IntegerField(validators=[django.core.validators.MaxValueValidator(500)])),
                ('backlight', models.BooleanField()),
                ('glass', models.CharField(max_length=255)),
                ('calendar_day', models.BooleanField()),
                ('calendar_date', models.BooleanField()),
                ('calendar_full', models.BooleanField()),
                ('size', models.CharField(max_length=255)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productbrand')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
            ],
        ),
    ]
