# Generated by Django 4.2.7 on 2023-11-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(max_length=255, verbose_name='Just a category name'),
        ),
    ]
