# Generated by Django 4.2.7 on 2023-11-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='calendar_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='calendar_day',
        ),
        migrations.RemoveField(
            model_name='product',
            name='calendar_full',
        ),
        migrations.AddField(
            model_name='product',
            name='calendar',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
