# Generated by Django 4.2.7 on 2023-11-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='brand_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
